from tkinter import *
my=Tk()
k=Tk()
my.title("first")
k.title("hello")
k.geometry("500x500+0+00")
my.geometry("500x500+500+100")
def main():
    K=l.get()
    label1=Label(my,text=K).pack()
def remain():
    K=m.get()
    label2=Label(k,text=K).pack()
l=StringVar()
m=StringVar()
mymenu=Menu()
listone=Menu()
listtwo=Menu()
listthree=Menu()
listfour=menu()
listfour.add_command(label="Run Module")
listfour.add_command(label="Compile Module")
listthree.add_command(label="Text File")
listthree.add_command(label="Audio File")
listthree.add_command(label="Video File")
listtwo.add_command(label="Undo")
listtwo.add_command(label="Redo")
listone.add_command(label="New File")
listone.add_command(label="Open File")
listone.add_command(label="Save File")
mymenu.add_cascade(label='File')
mymenu.add_cascade(label='Edit')
mymenu.add_cascade(label='Format')
mymenu.add_cascade(label='Run')
my.config(menu=mymenu)
button1=Button(my,text="click",fg="red",bg='yellow',command=main,font=100).pack()
button2=Button(k,text="ENTER",fg="blue",bg='yellow',command=remain,font='5000')
button2.pack()
text=Entry(textvariable=l).pack()
text1=Entry(textvariable=m).pack()
k.mainloop()
